# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8efe49bbae37ecd783ec41c5c71cb2deed70868c6d12f1bab1db1e8874f086f740005864480cc36d9645f7553cdf98f5473d89ed8d756097c9faf802bda05076

test:
  secret_key_base: 82f88e312cc768a0187b77ed1092e0965bdd4d97cedbba68b02553acf7446009da33a749f34ce1fb63a7f10b6d09e376c0bd729c09b920a8e328097c37fa0295

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
